version: '3'
services:
  mega_backup:
    build: .
    container_name: mega_backup
    hostname: mega_backup
    env_file: conf/mega_backup.env
    restart: always
    volumes:
      - ./:/usr/src/app
    command: bash -c 'python -u main.py'
